/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "proprueba_constants.h"



const propruebaConstants g_proprueba_constants;

propruebaConstants::propruebaConstants() {
}



