/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef proprueba_CONSTANTS_H
#define proprueba_CONSTANTS_H

#include "proprueba_types.h"



class propruebaConstants {
 public:
  propruebaConstants();

};

extern const propruebaConstants g_proprueba_constants;



#endif
